config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/gamehub' => 'games#index'
  
  resources :games
  resources :experiences

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/leaderboard', to: 'users#index', via: 'get'
  match '/signup',      to:'users#new',    via: 'get'
  match '/signin',      to:'sessions#new', via: 'get'
  match '/signout',     to:'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :experiences
  has_many :games

  validates :username, presence: true, length: { minimum: 5, maximum: 50 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+\.[a-z]+\z/i
  validates :email, presence:true , format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: {minimum: 8, maximum: 14}

  has_secure_password

  before_create :create_remember_token

  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  ## search queries

  #returns count of how many times a game has been played
  scope :game_plays, -> { joins(:experiences).
                           group("experiences.game_id").
                           count }

  #returns ordered array of users based on number of plays of their games
  scope :author_plays, -> { joins(:games).
                            group("games.user_id").
                            order("count() DESC") }

  #returns ordered array of users based on number of plays
  scope :user_plays, -> { joins(:experiences).
                           group("experiences.user_id").
                           order("count() DESC") }


   private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,  except: [:new, :create]
  before_action :correct_user,      only: [:edit, :update]
  before_action :update_ranks,      only: [:index]
  include UsersHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Text Kingdom"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @games_played = games_played(@user)
    @games_authored = authored_games(@user)
  end

  def index
    @author_table = @ranked_auths.paginate(page: params[:page], per_page: 10)
    @player_table = @ranked_plays.paginate(page: params[:page], per_page: 10)
  end

  # def destroy
  #   how to destroy user

  #   redirect_to users_path
  # end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    #could be optimized?
    def update_ranks
      # @ranked_auths = User.author_plays
      ranked_auths = User.all.to_a.sort_by! { |user| total_plays_of_author(user) }
      @ranked_auths = ranked_auths.reverse
      @ranked_plays = User.user_plays 
    end

end

app/helpers/users_helper.rb
module UsersHelper
  #for authoring

  def total_plays_of_author(user)
   user.games.joins(:experiences).
              group("experiences.game_id").
              count.
              values.
              inject(0,:+)
  end

  def avg_ratings_of_author(user)
    ratings_arr = user.games.joins(:experiences).group("experiences.game_id").average(:rating).values
    if ratings_arr == []
      return '---'
    else
      avg = (ratings_arr.inject(0, :+))/(ratings_arr.length)
      return avg.round(1)
    end
  end

  def top_game(user)
    highest_rated_game = user.games[0]
    if !highest_rated_game.nil?
      user.games.each do |game|
       if avg_game_rating(game) > avg_game_rating(highest_rated_game)
         highest_rated_game = game
        end
      end
      return highest_rated_game.title
    else
      return '---'
    end
  end

  def top_game_record(user)
    highest_rated_game = user.games[0]
    if !highest_rated_game.nil?
      user.games.each do |game|
       if avg_game_rating(game) > avg_game_rating(highest_rated_game)
         highest_rated_game = game
        end
      end
      return highest_rated_game
    else
      return none
    end
  end

  def num_games_played(user)
    user.experiences.uniq.count
  end

  def games_played(user)
    game_ids = Experience.where(user: user.id).pluck("game_id")
    return Game.where(:id => game_ids)
  end

  def authored_games(user)
    Game.where(user: user)
  end

end

app/views/users/edit.html.erb
<div class= 'center'>
<h1>Update your Profile!</h1>

<div class="center form-container">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :first_name, class: 'label'%>
      <%= f.text_field :first_name, class: 'input' %>
      <br>

      <%= f.label :last_name, class: 'label' %>
      <%= f.text_field :last_name, class: 'input' %>
      <br>

      <%= f.label :username, class: 'label' %>
      <%= f.text_field :username, class: 'input' %>
      <br>
      <%= f.label :email, class: 'label' %>
      <%= f.text_field :email, class: 'input' %>
      <br>
      <%= f.label :password, class: 'label' %>
      <%= f.password_field :password, class: 'input' %>
      <br>

      <%= f.label :password_confirmation, "Confirmation", class: "label" %>
      <%= f.password_field :password_confirmation, class: 'input' %>
      <br>


      <%= f.submit "Save", class: "btn btn-large btn-primary sign-in" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="center">
<h1> LeaderBoard </h1>

<div class="panel panel-default newest">
	  <div class="panel-heading">
	    <h3 class="panel-title">Leading Players</h3>
	  </div>
	  <div class="panel-body">
	    Panel content
	  </div>

	  <!-- Table -->
		<%= will_paginate @player_table%>
	  <table class="table">
		<tr>
		  <th>Rank</th>
		  <th>Username</th>
		  <th class="plays">Total Plays</th>
		  <th class="rating">Total Score</th>
		</tr>

		<!-- Pull subsequent rows from db -->
		<% @player_table.each_with_index do |user, i| %>
			<tr>
			  <td><%= (i+1).to_s %> </td>
			  <td><%= link_to user.username, user_path(user) %></td> 
			  <td><%= num_games_played(user) %></td>
			  <td>Score?</td>
			</tr>
		<% end %>
  	  </table>
		<%= will_paginate @player_table %>
</div>

<div class="panel panel-default newest">
	  <div class="panel-heading">
	    <h3 class="panel-title">Leading Authors</h3>
	  </div>
	  <div class="panel-body">
	    Panel content
	  </div>

	  <!-- Table -->
	  <%= will_paginate @author_table%>
	  <table class="table">
		<tr>
		  <th>Username</th>
		  <th class="plays">Total Plays</th>
		  <th class="rating">Average Rating</th>
		  <th>Top Game</th>
		  <th></th>
		</tr>

	
		<!-- Pull subsequent rows from db -->
		<% @author_table.each_with_index do |user, i| %>
			<tr>
			  <td><%= link_to user.username, user_path(user) %></td>
			  <td><%= total_plays_of_author(user) %></td> 
			  <td><%= avg_ratings_of_author(user) %></td>
			  <td><%= top_game(user) %></td>
			  <td><%= link_to "Play!", game_path(top_game_record(user)), class: "play-now btn" %></td>
			</tr>
		<% end %>
  	  </table>
		<%= will_paginate @author_table %>
</div>

</div>

app/views/users/new.html.erb
<div class="center">
<h1>Sign up</h1>

<div class="center form-container">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :first_name, class: 'label' %>
      <%= f.text_field :first_name, class: 'input' %>
      <br>


      <%= f.label :last_name, class: 'label' %>
      <%= f.text_field :last_name, class: 'input' %>
      <br>

      <%= f.label :username, class: 'label' %>
      <%= f.text_field :username, class: 'input' %>
      <br>
 

      <%= f.label :email, class: 'label' %>
      <%= f.text_field :email, class: 'input' %>
      <br>

      <%= f.label :password, class: 'label' %>
      <%= f.password_field :password, class: 'input' %>
      <br>

      <%= f.label :password_confirmation, "Confirmation", class: 'label' %>
      <%= f.password_field :password_confirmation, class: 'input' %>
      <br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary sign-in" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="center">

  <div class="user-profile">
    <div class= "profile-left">
      <div class='name'><%= @user.username %></div>
      <%= @user.first_name unless @user.first_name.nil? %>
      <%= @user.last_name unless @user.last_name.nil? %>
      <br>
      <br>
      <%if current_user? (@user) %>
      <%= link_to "Edit Profile", edit_user_path(@user), class: 'btn' %>
      <% end %>
    </div>
    <div class="profile-right ">
      <table class="table">
        <tr>
        <th>Game Stats</th>
        </tr>
        <%if current_user? (@user) %>
        <tr>
        <td><%= link_to "Upload a New Game", new_game_path, class: "upload-game btn" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="panel panel-default user-played-games">
    <div class="panel-heading">
      <h3 class="panel-title">Recently Played</h3>
    </div>
    <!-- Table -->
    <table class="table">
    <tr>
      <th class="title">Title</th>
      <th class="author">Author</th> 
      <th class="plays">Plays</th>
      <th class="rating"> Rating</th>
      <th class="prog">Progress</th>
    </tr>

    <!-- Pull subsequent rows from db -->
    <% @games_played.each do |game| %>
    <tr>
      <td><%= game.title %></td>
      <td><%= link_to game.user.username, user_path(game.user) %></td> 
      <td><%= plays(game) %></td>
      <td><%= rating(game) %></td>
      <td>100%</td>
      <% if current_user? (@user) %>
      <td><%= link_to "Finish!", game_path(game), class: "play-now btn" %></td>
      <% else %>
      <td><%= link_to "Play!", game_path(game), class: "play-now btn" %></td>
      <% end %>

    </tr>
    <% end %>
      </table>
  </div>

  <div class="panel panel-default user-played-games">
    <div class="panel-heading">
      <h3 class="panel-title">My Games</h3>
    </div>
    <!-- Table -->
    <table class="table">
    <tr>
      <th class="title">Title</th>
      <th class="author">Author</th> 
      <th class="plays">Plays</th>
      <th class="rating"> Rating</th>
    </tr>

    <!-- Pull subsequent rows from db -->
     <% @games_authored.each do |game| %>
    <tr>
      <td><%= link_to game.title, game_path(game) %></td>
      <td><%= game.user.username %></td> 
      <td><%= plays(game) %></td>
      <td><%= rating(game) %></td>
    </tr>
    <% end %>
      </table>
  </div>


</div>