config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/gamehub' => 'games#index'
  
  resources :games
  resources :experiences

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/leaderboard', to: 'users#index', via: 'get'
  match '/signup',      to:'users#new',    via: 'get'
  match '/signin',      to:'sessions#new', via: 'get'
  match '/signout',     to:'sessions#destroy', via: 'delete'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  has_many :experiences

  validates :user, presence: true
  validates :link, presence: true
  validates :description, presence: true
  validates :title, presence: true
  validates :genre, presence: true

  scope :games_week, -> { where(:created_at => 1.week.ago..Time.now).
                          joins(:experiences).
                          group("experiences.game_id").
                          order("count(experiences.game_id) DESC") }
 
 scope :games_year, -> { where(:created_at => 1.year.ago..Time.now).
                          joins(:experiences).
                          group("experiences.game_id").
                          order("count(experiences.game_id) DESC") }
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  #Not sure yet the way to add and create new games

   def new
     @game = Game.new
   end

   def create
    @game = Game.new(game_params)
    @game.user = current_user
    if @game.save
      flash[:success] = "Your game is live!"
      redirect_to @game
    else
      render 'new'
    end
   end

   def show
    @game = Game.find(params[:id])
    @experience = Experience.find_by(user: current_user, game: @game) || Experience.new(rating: 0, progress: 0, game: @game, user: current_user)
   end

  def index
    #Game Hub page
    @game_newest = Game.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    @game_week = Game.games_week.paginate(page: params[:page], per_page: 10)
    @game_year = Game.games_year.paginate(page: params[:page], per_page: 10) 
  end

  private
    def game_params
      params.require(:game).permit(:title, :link, :description, :genre)
    end
end

app/helpers/games_helper.rb
module GamesHelper
	def rating (game)
      game.experiences.average(:rating).to_f.round(1)
  end

  def plays(game)
    game.experiences.count
  end

  def game_total_plays (game)
      game.experiences.count
  end
end

app/views/games/index.html.erb
<div class="center">

	<h1> GameHub</h1>

	<form class="search" role="search">
  		<div class="search-component form-group">
    		<input type="text" class="form-control" placeholder="Search">
  		</div>
  		<button type="submit" class="search-component btn btn-default">Find</button>
	</form>

	<div class="genres panel-body">
	    <div class="row">
			<div class="col-md-4"><div id="fantasy" class="genre-panel"><h1>Fantasy</h1></div></div>
			<div class="col-md-4"><div id="mystery" class="genre-panel"><h1>Mystery</h1></div></div>
			<div class="col-md-4"><div id="dungeon" class="genre-panel"><h1>Dungeon</h1></div></div>
		</div>
	</div>
	
	<div class="panel panel-default newest">
	  <div class="panel-heading">
	    <h3 class="panel-title">Newest Games</h3>
	  </div>
	  <div class="panel-body">
	    Panel content
	  </div>

	  <%= will_paginate @game_newest %>
	  <!-- Table -->
	  <table class="table">
		<tr>
		  <th>Title</th>
		  <th>Author</th> 
		  <th class="plays">Plays</th>
		  <th class="rating">Rating</th>
		  <th></th>
		</tr>

		<!-- Pull subsequent rows from db -->
		<% @game_newest.each do |game| %>
			<tr>
			  <td><%= game.title %></td>
			  <td><%= link_to game.user.username, user_path(game.user) %></td> 
			  <td><%= plays(game) %> <td>
			  <td><%= rating(game) %></td>
			  <td><%= link_to "Play!", '/games/' + game.id.to_s, class: "play-now btn" %></td>
			</tr>
		<% end %>
  	  </table>
  	  <%= will_paginate @game_newest %>

	</div>
	
	<div class="panel panel-default top-week">
	  <div class="panel-heading">
	    <h3 class="panel-title">Top of Week</h3>
	  </div>
	  <div class="panel-body">
	    Panel content
	  </div>

	  <%= will_paginate @game_week %>
	  <!-- Table -->
	  <table class="table">
		<tr>
		  <th>Title</th>
		  <th>Author</th> 
		  <th class="plays">Plays</th>
		  <th class="rating">Rating</th>
		  <th></th>
		</tr>

		<!-- Pull subsequent rows from db -->
		<% @game_week.each do |game| %>
			<tr>
			  <td><%= game.title %></td>
			  <td><%= link_to game.user.username, user_path(game.user) %></td> 
			  <td><%= plays(game) %> <td>
			  <td><%= rating(game) %></td>
			  <td><%= link_to "Play!", '/games/' + game.id.to_s, class: "play-now btn" %></td>
			</tr>
		<% end %>
  	  </table>
  	  <%= will_paginate @game_week %>
	</div>
	
	<div class="panel panel-default top-year">
	  <div class="panel-heading">
	    <h3 class="panel-title">Top Games this Year</h3>
	  </div>
	  <div class="panel-body">
	    Panel content
	  </div>

	  <%= will_paginate @game_year %>
	  <!-- Table -->
	  <table class="table">
		<tr>
		  <th>Title</th>
		  <th>Author</th> 
		  <th class="plays">Plays</th>
		  <th class="rating">Rating</th>
		  <th></th>
		</tr>

		<!-- Pull subsequent rows from db -->
		<% @game_year.each do |game| %>
			<tr>
			  <td><%= game.title %></td>
			  <td><%= link_to game.user.username, user_path(game.user) %></td> 
			  <td><%= plays(game) %> <td>
			  <td><%= rating(game) %></td>			  <td><%= link_to "Play!", '/games/' + game.id.to_s, class: "play-now btn" %></td>
			</tr>
		<% end %>
  	  </table>
  	  <%= will_paginate @game_year %>
	</div>

</div>

app/views/games/new.html.erb
<div class='center'>
<h1>Make a Game!</h1>

<div class="center form-container">
  <div class="span6 offset3">
    <%= form_for(@game) do |f| %>

      <%= render 'shared/game_error_messages' %>

      <%= f.label :title, class: 'label' %>
      <%= f.text_field :title, class: 'input' %>
      <br>


      <%= f.label :link, class: 'label' %>
      <%= f.text_field :link, class: 'input' %>
      <br>

      <%= f.label :description, class: 'label' %>
      <%= f.text_field :description, class: 'input'  %>
      <br>
 

      <%= f.label :genre, class: 'label' %>
      <%= f.text_field :genre, class: 'input'  %>
      <br>

      <%= f.submit "Create Game", class: "btn btn-large btn-primary sign-in" %>
    <% end %>
  </div>
</div>
</div>

app/views/games/show.html.erb
<%= render 'navbar' %>
<div class="center">

  <div class="user-profile">
    <div class= "profile-left">
      <div class="name"><%= @game.title %></div>
      <%if current_user? (@game.user) %>
        <%= link_to "Edit Game", edit_game_path(@game), class: 'btn' %>
      <% end %>

      <table class="table">
        <tr>
          <th>Rating</th>
          <th>Plays</th>
        </tr>
        <tr>
          <td><%= rating(@game) %>/10</td>
          <td><%= game_total_plays(@game) %></td>
        </tr>
      </table>
    </div>

    <div class="profile-right">

      <img src='http://i.kinja-img.com/gawker-media/image/upload/s--F_SVgFM9--/c_fit,fl_progressive,q_80,w_636/18kgudf97suzupng.png'>

      <%= form_for(@experience) do |f| %>

        <%= f.label :rating %>
        <%= f.number_field :rating, in: 1..10, value: @experience.rating %>

        <%= f.label :progress %>
        <%= f.number_field :progress, in: 1..100, value: @experience.progress %>

        <%= f.hidden_field :user, value: current_user.id %>
        <%= f.hidden_field :game, value: @game.id %>

        <%= f.submit "Save", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
</div>