config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/gamehub' => 'games#index'
  
  resources :games
  resources :experiences

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/leaderboard', to: 'users#index', via: 'get'
  match '/signup',      to:'users#new',    via: 'get'
  match '/signin',      to:'sessions#new', via: 'get'
  match '/signout',     to:'sessions#destroy', via: 'delete'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include GamesHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  #average rating of a game

    def avg_game_rating(game)
      sum = 0
      n = 0
      game.experiences.each do |play|
        play.rating += sum
        n += 1
      end
      n != 0 ? avg = (sum/n).round(1) : avg = 0.0
    end

  def rating (game)
      game.experiences.average(:rating).to_f.round(1)
  end

  def plays(game)
    game.experiences.count
  end

  def game_total_plays (game)
      game.experiences.count
  end




end

app/views/application/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">TextKingdom</a>
    by Tim Follo & Amy Rockwood
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://www.bbc.com/news/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/application/_navbar.html.erb
<!-- Nav bar helper -->
<!-- inject with  #render 'navbar' -->

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TextKingdom", '/about', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "GameHub", '/gamehub' %></li>
          <li><%= link_to "Leaderboard", '/leaderboard' %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path , method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>